name: ${VRCA_CLIENT_CONTAINER_NAME}

networks:
  vircadia_network:
    driver: bridge

services:
  # Production Web Babylon JS Client (Optimized Build)
  web_babylon_js_prod:
    image: oven/bun:1.2.5-alpine
    container_name: web_babylon_js_prod
    user: "1000:1000"  # Run as non-root user
    restart: always
    ports:
      - "${VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_HOST_CONTAINER_BIND_EXTERNAL}:${VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_BIND_EXTERNAL}:${VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_INTERNAL}"
    volumes:
      - ./web_babylon_js/volume:/app
    working_dir: /app/app
    command: ["bun", "run", "deploy"]
    environment:    
      VRCA_CLIENT_WEB_BABYLON_JS_DEBUG: ${VRCA_CLIENT_WEB_BABYLON_JS_DEBUG}
      VRCA_CLIENT_WEB_BABYLON_JS_SUPPRESS: ${VRCA_CLIENT_WEB_BABYLON_JS_SUPPRESS}
      VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_INTERNAL: ${VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_INTERNAL}
      VRCA_CLIENT_WEB_BABYLON_JS_DEBUG_SESSION_TOKEN: ${VRCA_CLIENT_WEB_BABYLON_JS_DEBUG_SESSION_TOKEN}
      VRCA_CLIENT_WEB_BABYLON_JS_META_TITLE_BASE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_TITLE_BASE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_DESCRIPTION: ${VRCA_CLIENT_WEB_BABYLON_JS_META_DESCRIPTION}
      VRCA_CLIENT_WEB_BABYLON_JS_META_OG_IMAGE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_OG_IMAGE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_OG_TYPE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_OG_TYPE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_FAVICON: ${VRCA_CLIENT_WEB_BABYLON_JS_META_FAVICON}
      VRCA_CLIENT_WEB_BABYLON_JS_APP_URL: ${VRCA_CLIENT_WEB_BABYLON_JS_APP_URL}
      VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI: ${VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI}
      VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI_USING_SSL: ${VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI_USING_SSL}
    healthcheck:
      test: ["CMD-SHELL", "cd ../vircadia-world-sdk-ts && bun i && cd ../test && bun test"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - vircadia_network

  # Development Web Babylon JS Client (Hot Reloading)
  web_babylon_js_dev:
    image: oven/bun:1.2.5-alpine
    container_name: web_babylon_js_dev
    user: "1000:1000"  # Run as non-root user
    restart: "no"  # Don't auto-restart in development
    ports:
      - "${VRCA_CLIENT_WEB_BABYLON_JS_DEV_HOST_CONTAINER_BIND_EXTERNAL}:${VRCA_CLIENT_WEB_BABYLON_JS_DEV_PORT_CONTAINER_BIND_EXTERNAL}:${VRCA_CLIENT_WEB_BABYLON_JS_DEV_PORT_CONTAINER_INTERNAL}"
    volumes:
      - ./web_babylon_js/volume:/app
    working_dir: /app/app
    command: ["bun", "run", "dev"]
    environment:    
      VRCA_CLIENT_WEB_BABYLON_JS_DEBUG: "true"  # Always debug in development
      VRCA_CLIENT_WEB_BABYLON_JS_SUPPRESS: "false"  # Don't suppress logs in development
      VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_INTERNAL: ${VRCA_CLIENT_WEB_BABYLON_JS_PRODUCTION_PORT_CONTAINER_INTERNAL}
      VRCA_CLIENT_WEB_BABYLON_JS_DEBUG_SESSION_TOKEN: ${VRCA_CLIENT_WEB_BABYLON_JS_DEBUG_SESSION_TOKEN}
      VRCA_CLIENT_WEB_BABYLON_JS_META_TITLE_BASE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_TITLE_BASE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_DESCRIPTION: ${VRCA_CLIENT_WEB_BABYLON_JS_META_DESCRIPTION}
      VRCA_CLIENT_WEB_BABYLON_JS_META_OG_IMAGE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_OG_IMAGE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_OG_TYPE: ${VRCA_CLIENT_WEB_BABYLON_JS_META_OG_TYPE}
      VRCA_CLIENT_WEB_BABYLON_JS_META_FAVICON: ${VRCA_CLIENT_WEB_BABYLON_JS_META_FAVICON}
      VRCA_CLIENT_WEB_BABYLON_JS_APP_URL: ${VRCA_CLIENT_WEB_BABYLON_JS_APP_URL}
      VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI: ${VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI}
      VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI_USING_SSL: ${VRCA_CLIENT_WEB_BABYLON_JS_DEFAULT_WORLD_SERVER_URI_USING_SSL}
    networks:
      - vircadia_network