name: ${VRCA_SERVER_CONTAINER_NAME}

networks:
  vircadia_network:
    driver: bridge

volumes:
  postgres_data:
    name: "${VRCA_SERVER_CONTAINER_NAME}_postgres_data"

services:
  # Postgres service
  postgres:
    image: postgres:17.3-alpine3.21
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_postgres
    user: "70:70"  # Alpine postgres user (UID:GID)
    restart: always
    environment:
      POSTGRES_DB: ${VRCA_SERVER_SERVICE_POSTGRES_DATABASE}
      POSTGRES_USER: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME}  # This user gets superuser privileges by default
      POSTGRES_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD}
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - "${VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_EXTERNAL}:${VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_EXTERNAL}:5432"
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql:uid=70,gid=70,exec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL", 
        "pg_isready -U ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME} -d ${VRCA_SERVER_SERVICE_POSTGRES_DATABASE} && psql -U ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME} -d ${VRCA_SERVER_SERVICE_POSTGRES_DATABASE} -c \"SELECT COUNT(*) FROM config.seeds\" | grep -q '[1-9]'"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vircadia_network

  # PGWEB service
  pgweb:
    image: sosedoff/pgweb:0.16.2
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_pgweb
    user: "1000:1000"  # Run as non-root user (typical first user UID/GID)
    restart: always
    ports:
      - "${VRCA_SERVER_SERVICE_PGWEB_HOST_CONTAINER_EXTERNAL}:${VRCA_SERVER_SERVICE_PGWEB_PORT_CONTAINER_EXTERNAL}:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME}:${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD}@${VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_CLUSTER}:${VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_CLUSTER}/${VRCA_SERVER_SERVICE_POSTGRES_DATABASE}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache
      - /var/log
      - /home/pgweb/.pgweb/bookmarks
      - /home/pgweb/.pgweb/sessions
      - /home/pgweb/.pgweb/queries
    volumes:
      - ./pgweb/volume/test:/app/test
    networks:
      - vircadia_network

  # API service
  api:
    image: oven/bun:1.2.5-alpine
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_api
    user: "1000:1000"  # Run as non-root user
    restart: always
    ports:
      - "${VRCA_SERVER_SERVICE_API_HOST_CONTAINER_EXTERNAL}:${VRCA_SERVER_SERVICE_API_PORT_CONTAINER_EXTERNAL}:3020"
    volumes:
      - ./api/volume:/app
    working_dir: /app
    command: ["bun", "run", "--watch", "/app/app/world.api.manager.ts"]
    environment:
      VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME}
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_USERNAME: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_USERNAME}
    
      VRCA_SERVER_DEBUG: ${VRCA_SERVER_DEBUG}
      VRCA_SERVER_SUPPRESS: ${VRCA_SERVER_SUPPRESS}

      VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_CLUSTER: ${VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_CLUSTER}
      VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_CLUSTER: ${VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_CLUSTER}
      VRCA_SERVER_SERVICE_POSTGRES_DATABASE: ${VRCA_SERVER_SERVICE_POSTGRES_DATABASE}
      VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD}
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "cd vircadia-world-sdk-ts && bun i && cd ../test && bun test"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - vircadia_network

  # Tick service
  tick:
    image: oven/bun:1.2.5-alpine
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_tick
    user: "1000:1000"  # Run as non-root user
    restart: always
    ports:
      - "${VRCA_SERVER_SERVICE_TICK_HOST_CONTAINER_EXTERNAL}:${VRCA_SERVER_SERVICE_TICK_PORT_CONTAINER_EXTERNAL}:3020"
    volumes:
      - ./tick/volume:/app
    working_dir: /app
    command: ["bun", "run", "--watch", "/app/app/world.tick.manager.ts"]
    environment:
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_USERNAME: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_USERNAME}
      VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_USERNAME}

      VRCA_SERVER_DEBUG: ${VRCA_SERVER_DEBUG}
      VRCA_SERVER_SUPPRESS: ${VRCA_SERVER_SUPPRESS}

      VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_CLUSTER: ${VRCA_SERVER_SERVICE_POSTGRES_HOST_CONTAINER_CLUSTER}
      VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_CLUSTER: ${VRCA_SERVER_SERVICE_POSTGRES_PORT_CONTAINER_CLUSTER}
      VRCA_SERVER_SERVICE_POSTGRES_DATABASE: ${VRCA_SERVER_SERVICE_POSTGRES_DATABASE}
      VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD}
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "cd vircadia-world-sdk-ts && bun i && cd ../test && bun test"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - vircadia_network
