services:
  pgweb:
    image: sosedoff/pgweb:0.16.2
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_pgweb
    user: "1000:1000"  # Run as non-root user (typical first user UID/GID)
    restart: always
    ports:
      - "${PGWEB_PORT}:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${VRCA_SERVER_SERVICE_POSTGRES_USER}:${VRCA_SERVER_SERVICE_POSTGRES_PASSWORD}@${VRCA_SERVER_CONTAINER_NAME}_postgres:5432/${VRCA_SERVER_SERVICE_POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache
      - /var/log
      - /home/pgweb/.pgweb/bookmarks
      - /home/pgweb/.pgweb/sessions
      - /home/pgweb/.pgweb/queries
    volumes:
      - ./volume/test:/app/test
    networks:
      - vircadia_network