services:
  script_web:
    image: oven/bun:1.2.4-slim
    container_name: ${VRCA_SERVER_CONTAINER_NAME}_script_web
    user: "1000:1000"  # Run as non-root user
    restart: always
    volumes:
      - ./volume:/app
    working_dir: /app
    command: ["bun", "run", "--watch", "/app/app/world.web.script.manager.ts"]
    environment:
      VRCA_SERVER_DEBUG: ${VRCA_SERVER_DEBUG}
      VRCA_SERVER_SUPPRESS: ${VRCA_SERVER_SUPPRESS}
      VRCA_SERVER_SERVICE_POSTGRES_HOST: ${VRCA_SERVER_SERVICE_POSTGRES_HOST}
      VRCA_SERVER_SERVICE_POSTGRES_PORT: ${VRCA_SERVER_SERVICE_POSTGRES_PORT}
      VRCA_SERVER_SERVICE_POSTGRES_DB: ${VRCA_SERVER_SERVICE_POSTGRES_DB}
      VRCA_SERVER_SERVICE_POSTGRES_USER: ${VRCA_SERVER_SERVICE_POSTGRES_USER}
      VRCA_SERVER_SERVICE_POSTGRES_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_PASSWORD}
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER}
      VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_PASSWORD: ${VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bun", "test", "/app/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - vircadia_network