name: ${CONTAINER_NAME}
services:
  postgres:
    image: postgres:12.22-bookworm
    container_name: ${CONTAINER_NAME}_postgres
    # Note: POSTGRES_USER is automatically created as a superuser
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}  # This user gets superuser privileges by default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTENSIONS: ${POSTGRES_EXTENSIONS}
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vircadia_world_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vircadia_network

  pgweb:
    image: sosedoff/pgweb
    container_name: ${CONTAINER_NAME}_pgweb
    restart: always
    ports:
      - "${PGWEB_PORT}:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_NAME}_postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - vircadia_network

networks:
  vircadia_network:
    driver: bridge

volumes:
  vircadia_world_postgres_data:
