name: ${CONTAINER_NAME}
services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTENSIONS: ${POSTGRES_EXTENSIONS}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vircadia_world_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: ${CONTAINER_NAME}_caddy
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "${POSTGRES_API_PORT}:${POSTGRES_API_PORT}"
    volumes:
      - ../../proxy/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - vircadia_world_caddy_data:/data
      - vircadia_world_caddy_config:/config
    environment:
      - POSTGRES_API_PORT=${POSTGRES_API_PORT}
    restart: unless-stopped

volumes:
  vircadia_world_postgres_data:
  vircadia_world_caddy_data:
  vircadia_world_caddy_config:
